name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Text File
        run: |
          echo "This is a simple text file for GitHub Pages." > build/index.txt

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3  # Correct action version for upload

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3  # Correct action version for deploy
